# Generated by Django 5.2.9 on 2026-05-21 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('Оценка 360', 'Оценка 360'), ('Чек-лист', 'Чек-лист'), ('Опросник', 'Опросник')], max_length=10)),
                ('status', models.CharField(choices=[('Запланирована', 'Запланирована'), ('Активна', 'Активна'), ('Завершена', 'Завершена')], max_length=13)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='По умолчанию', max_length=100)),
                ('status', models.CharField(choices=[('Активная', 'Активная'), ('Неактивная', 'Неактивная')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='IndicatorQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=500)),
                ('answer_positive', models.TextField(max_length=500)),
                ('answer_neutral', models.TextField(max_length=500)),
                ('answer_negative', models.TextField(max_length=500)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='api.indicator')),
            ],
        ),
        migrations.CreateModel(
            name='QualityIndicatorRatio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratio', models.FloatField(default=0.0)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratios_to_qualities', to='api.indicator')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualities_ratios', to='api.assessmentmodel')),
                ('quality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratios_to_indicators', to='api.quality')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentFormTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='api.assessmentform')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='api.team')),
            ],
        ),
        migrations.CreateModel(
            name='IndicatorTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.indicator')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.template')),
            ],
        ),
        migrations.AddField(
            model_name='assessmentform',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='api.template'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('email', models.CharField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, default='default_avatar.jpeg', upload_to='users_photo/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='template',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_templates', to='api.userprofile'),
        ),
        migrations.AddField(
            model_name='team',
            name='tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='api.userprofile'),
        ),
        migrations.CreateModel(
            name='Scores360Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('score', models.FloatField(default=0.0)),
                ('form', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='api.assessmentform')),
                ('quality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores_360', to='api.quality')),
                ('evaluated_projectant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_360_scores', to='api.userprofile')),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluated_360_scores', to='api.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='QualitiesScoreRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scores_count', models.IntegerField(default=1)),
                ('score', models.FloatField(default=0.0)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualities', to='api.assessmentmodel')),
                ('quality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_scores', to='api.quality')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualities_scores', to='api.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='IndicatorScoresRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators_scores', to='api.assessmentform')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='api.indicator')),
                ('evaluated_projectant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_indicators_scores', to='api.userprofile')),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluated_indicators_scores', to='api.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='AverageIndicatorScoresRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_score', models.FloatField(default=0.0)),
                ('scores_count', models.IntegerField(default=1)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='average_scores', to='api.indicator')),
                ('projectant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='average_indicator_scores', to='api.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_team', to='api.team')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_member', to='api.userprofile')),
            ],
            options={
                'unique_together': {('team', 'member')},
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Проектант', 'Проектант'), ('Куратор', 'Куратор'), ('Организатор', 'Организатор')], default='Проектант', max_length=24)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_owner', to='api.userprofile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'role'), name='unique_user_role')],
            },
        ),
    ]
