# Generated by Django 5.2.9 on 2026-05-19 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='PollQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('question_type', models.CharField(choices=[('rating', 'Оценка (1-5)'), ('text', 'Текстовый ответ'), ('choice', 'Выбор варианта')], default='rating', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('required', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PollTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CompetenceIndicatorRatio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratio', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competence_indicator_related', to='api.competence')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator', to='api.indicator')),
            ],
        ),
        migrations.CreateModel(
            name='IndicatorsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator_1', to='api.indicator')),
                ('indicator2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator_2', to='api.indicator')),
                ('indicator3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator_3', to='api.indicator')),
                ('indicator4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator_4', to='api.indicator')),
                ('indicator5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator_5', to='api.indicator')),
            ],
        ),
        migrations.CreateModel(
            name='IndicatorsListTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('indicators_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.indicatorslist')),
            ],
        ),
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('value', models.IntegerField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='api.pollquestion')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='pollquestion',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.polltemplate'),
        ),
        migrations.CreateModel(
            name='QualityCompetenceRatio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.CharField(choices=[('Обучаемость', 'Обучаемость'), ('Вовлеченность', 'Вовлеченность'), ('Организованность', 'Организованность'), ('Работа в команде', 'Работа в команде')])),
                ('ratio', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_competence_related', to='api.competence')),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('active', 'Активен'), ('closed', 'Закрыт')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='polls', to='api.polltemplate')),
                ('teams', models.ManyToManyField(related_name='polls', to='api.team')),
            ],
        ),
        migrations.CreateModel(
            name='TemplateCompetence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competences', to='api.indicatorslisttemplate')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True)),
                ('telegram', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, null=True)),
                ('vk', models.CharField(blank=True, max_length=100, null=True)),
                ('university', models.CharField(blank=True, max_length=200, null=True)),
                ('year_of_study', models.CharField(blank=True, max_length=4, null=True)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('photo', models.ImageField(blank=True, default='default_avatar.jpeg', upload_to='users_photo/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_team', to='api.team')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_member', to='api.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams_tutor', to='api.userprofile'),
        ),
        migrations.CreateModel(
            name='QualitiesScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('involvement_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('organization_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('teamwork_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualities_related_user', to='api.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='polltemplate',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_templates', to='api.userprofile'),
        ),
        migrations.CreateModel(
            name='PollAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_link', models.CharField(max_length=100, unique=True)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='api.poll')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_assignments', to='api.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='poll',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_polls', to='api.userprofile'),
        ),
        migrations.AddField(
            model_name='indicatorslisttemplate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_user', to='api.userprofile'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('name', models.CharField(default='Мероприятие', max_length=200)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_on_event', to='api.team')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_tutor', to='api.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CompetencesScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compentences_score_related_competence', to='api.competence')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compentences_score_related_user', to='api.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CheckList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_event', to='api.event')),
                ('indicators_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators_for_checklist', to='api.indicatorslist')),
                ('evaluated_projectant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Проектант', 'Проектант'), ('Куратор', 'Куратор'), ('Организатор', 'Организатор')], default='Проектант', max_length=24)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_owner', to='api.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ChecklistCompetence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competences', to='api.checklist')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('checklist', 'name')},
            },
        ),
        migrations.CreateModel(
            name='PollResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True, null=True)),
                ('answer_value', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answer_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.polloption')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='api.pollassignment')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pollquestion')),
            ],
            options={
                'unique_together': {('assignment', 'question')},
            },
        ),
        migrations.CreateModel(
            name='ChecklistScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.CharField(max_length=50)),
                ('score', models.IntegerField(blank=True, choices=[(-1, '-1'), (0, '0'), (1, '1')], null=True)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='api.checklist')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userprofile')),
            ],
            options={
                'unique_together': {('checklist', 'student', 'quality')},
            },
        ),
    ]
