# Generated by Django 5.2.9 on 2026-05-22 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentform',
            name='completed_by',
            field=models.ManyToManyField(blank=True, related_name='completed_forms', to='api.userprofile'),
        ),
    ]
