# Generated by Django 5.2.8 on 2026-05-19 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='quality',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
