# Generated by Django 5.2.8 on 2026-05-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_indicator_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentmodel',
            name='status',
            field=models.CharField(default='Активная', max_length=10),
        ),
    ]
