# Generated by Django 5.2.9 on 2026-05-22 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_assessmentform_completed_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentform',
            name='completed_by',
        ),
    ]
