# Generated by Django 5.2.9 on 2026-05-23 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_assessmentform_completed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentform',
            name='qualities',
            field=models.JSONField(blank=True, default=list, help_text='Список качеств для оценки'),
        ),
    ]
