# Generated by Django 5.2.8 on 2025-11-18 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_item_age_alter_item_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='user',
        ),
    ]
