# Generated by Django 5.2.8 on 2026-05-19 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_assessmentmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentmodel',
            name='status',
            field=models.CharField(choices=[('Активная', 'Активная'), ('Неактивная', 'Неактивная')], max_length=10),
        ),
    ]
