# Generated by Django 5.2.9 on 2026-05-23 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_assessmentform_qualities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentform',
            name='qualities',
        ),
    ]
