# Generated by Django 5.2.9 on 2025-12-28 07:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_userprofile_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualitiesscore',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qualitiesscore',
            name='evaluator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='evaluated_qualities', to='api.userprofile'),
            preserve_default=False,
        ),
    ]
