# Generated by Django 5.2.9 on 2026-05-23 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
