# Generated by Django 5.2.9 on 2025-12-28 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_qualitiesscore_created_at_qualitiesscore_evaluator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualitiesscore',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='qualitiesscore',
            name='evaluator',
        ),
    ]
