# Generated by Django 5.2.9 on 2026-03-03 17:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_qualitiesscore_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(default='Мероприятие', max_length=200),
        ),
        migrations.AddField(
            model_name='indicatorslisttemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indicatorslisttemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
