# Generated by Django 5.2.8 on 2025-11-18 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_user_delete_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user',
        ),
    ]
