# Generated by Django 5.2.9 on 2026-03-03 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_event_name_indicatorslisttemplate_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.CharField(max_length=50)),
                ('score', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3')], null=True)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='api.checklist')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userprofile')),
            ],
            options={
                'unique_together': {('checklist', 'student', 'quality')},
            },
        ),
    ]
