# Generated by Django 5.2.9 on 2026-03-04 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_checklistscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateCompetence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competences', to='api.indicatorslisttemplate')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
