# Generated by Django 5.2.9 on 2026-03-04 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_templatecompetence'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistCompetence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competences', to='api.checklist')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('checklist', 'name')},
            },
        ),
    ]
