# Generated by Django 5.2.9 on 2026-03-17 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_checklistcompetence'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=3)),
                ('week', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.competence')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_history', to='api.userprofile')),
            ],
            options={
                'ordering': ['week'],
                'unique_together': {('user', 'competence', 'week')},
            },
        ),
    ]
