# Generated by Django 5.2.9 on 2026-03-17 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_scorehistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScoreHistory',
        ),
    ]
