# Generated by Django 5.2.9 on 2026-04-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_pollquestion_poll_pollassignment_polloption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistscore',
            name='score',
            field=models.IntegerField(blank=True, choices=[(-1, '-1'), (0, '0'), (1, '1')], null=True),
        ),
    ]
